name: Bump Homebrew Cask

on:
  release:
    types: [published]

jobs:
  bump:
    runs-on: macos-10.15
    steps:
      - name: Bump Homebrew Cask
        run: brew bump-cask-pr bruno --version "${GITHUB_REF_NAME#v}"
